apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  type: LoadBalancer # Esto le dice a EKS que cree un ALB/NLB público en AWS
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: orders
    # ¡ESTE ES EL INTERRUPTOR MAGICO!
    # Cambia esto a "green" cuando quieras desviar el tráfico a la nueva versión
    version: green
